---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - logging.yago.ninja
  resources:
  - logshippers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.yago.ninja
  resources:
  - logshippers/finalizers
  verbs:
  - update
- apiGroups:
  - logging.yago.ninja
  resources:
  - logshippers/status
  verbs:
  - get
  - patch
  - update
