apiVersion: logs.yago.ninja/v1
kind: LogShip
metadata:
  labels:
    app.kubernetes.io/name: logkeeper
    app.kubernetes.io/managed-by: kustomize
  name: logship-sample
spec:
  # TODO(user): Add fields here
